In [1]:
import pandas as pd

# Load the dataset
df = pd.read_csv('evaluation/eval_results_updated.csv')
df.head()

,query,expected_file,expected_answer,search_time,chat_time,search_answer,search_toxicity,chat_answer,chat_toxicity,search_response,chat_response,ground_truth
0,What is tuberculosis?,FAQ.md,Tuberculosis (TB) is caused by a bacterium cal...,1.696,3.969,**A:** Tuberculosis (TB) is caused by a bacter...,NOT_TOXIC,Tuberculosis (TB) is caused by a bacterium cal...,NOT_TOXIC,"{""query"": ""What is tuberculosis?"", ""total_matc...","{""query"": ""What is tuberculosis?"", ""answer"": ""...",# Frequently Asked Questions (FAQ)\n\n*Sources...
1,How is TB spread?,FAQ.md,TB is spread through the air from one person t...,0.360,4.524,**A:** TB is spread through the air from one p...,NOT_TOXIC,TB is spread through the air from one person t...,NOT_TOXIC,"{""query"": ""How is TB spread?"", ""total_matches""...","{""query"": ""How is TB spread?"", ""answer"": ""TB i...",# Frequently Asked Questions (FAQ)\n\n*Sources...
2,What are the symptoms of TB disease?,Signs_and_Symptoms.md,The most common form of TB affects the lungs (...,0.468,3.670,**A:** Symptoms of TB disease depend on where ...,NOT_TOXIC,"According to the information provided, symptom...",NOT_TOXIC,"{""query"": ""What are the symptoms of TB disease...","{""query"": ""What are the symptoms of TB disease...",# Signs and Symptoms of Tuberculosis\n\n*Sourc...
3,What are the symptoms of TB in the brain?,Signs_and_Symptoms.md,TB of the Brain/Central Nervous System: Severe...,0.486,2.910,**A:** Symptoms of TB disease depend on where ...,NOT_TOXIC,"According to the information provided, symptom...",NOT_TOXIC,"{""query"": ""What are the symptoms of TB in the ...","{""query"": ""What are the symptoms of TB in the ...",# Signs and Symptoms of Tuberculosis\n\n*Sourc...
4,What is latent TB infection?,FAQ.md,Latent TB infection occurs when TB germs are i...,0.385,2.633,**A:** Latent TB infection occurs when TB germ...,NOT_TOXIC,Latent TB infection occurs when TB germs are i...,NOT_TOXIC,"{""query"": ""What is latent TB infection?"", ""tot...","{""query"": ""What is latent TB infection?"", ""ans...",# Frequently Asked Questions (FAQ)\n\n*Sources...

In [3]:
df['search_time'].describe().T

count    45.000000
mean      0.319378
std       0.253230
min       0.026000
25%       0.250000
50%       0.305000
75%       0.373000
max       1.696000
Name: search_time, dtype: float64

In [4]:
df['chat_time'].describe().T

count    45.000000
mean      3.075156
std       1.671914
min       0.023000
25%       2.653000
50%       3.353000
75%       3.917000
max       6.691000
Name: chat_time, dtype: float64

In [10]:
df2 = pd.read_csv("evaluation/eval_results_chunks.csv")
df2.head(2)

,query,expected_file,expected_answer,search_time,chat_time,search_answer,search_toxicity,chat_answer,chat_toxicity,search_response,chat_response,ground_truth
0,What is tuberculosis?,FAQ.md,Tuberculosis (TB) is caused by a bacterium cal...,1.696,3.969,**A:** Tuberculosis (TB) is caused by a bacter...,NOT_TOXIC,Tuberculosis (TB) is caused by a bacterium cal...,NOT_TOXIC,"{""query"": ""What is tuberculosis?"", ""total_matc...","{""query"": ""What is tuberculosis?"", ""answer"": ""...",# Frequently Asked Questions (FAQ)\n\n*Sources...
1,How is TB spread?,FAQ.md,TB is spread through the air from one person t...,0.360,4.524,**A:** TB is spread through the air from one p...,NOT_TOXIC,TB is spread through the air from one person t...,NOT_TOXIC,"{""query"": ""How is TB spread?"", ""total_matches""...","{""query"": ""How is TB spread?"", ""answer"": ""TB i...",# Frequently Asked Questions (FAQ)\n\n*Sources...

In [11]:
df2['ground_truth'].head(2)

0    # Frequently Asked Questions (FAQ)\n\n*Sources...
1    # Frequently Asked Questions (FAQ)\n\n*Sources...
Name: ground_truth, dtype: object

In [12]:
js = pd.read_json("chunks.json")
js.head(3)

,text,header,source_file,source_url
0,# TB Diagnosis Methods and Procedures\n\n*Sour...,,Diagnosis.md,https://www.who.int/news-room/fact-sheets/deta...
1,WHO recommends the use of **rapid molecular di...,## Overview,Diagnosis.md,https://www.who.int/news-room/fact-sheets/deta...
2,• **Xpert MTB/RIF Ultra**\n - High diagnostic...,#### Rapid Molecular Diagnostic Tests (Recomme...,Diagnosis.md,https://www.who.int/news-room/fact-sheets/deta...

In [13]:
dd = pd.read_csv("evaluation/eval_results_chunks_sentence.csv")
dd.head(2)

,query,expected_file,expected_answer,search_time,chat_time,search_answer,search_toxicity,chat_answer,chat_toxicity,search_response,chat_response,ground_truth,ground_truth_sentence
0,What is tuberculosis?,FAQ.md,Tuberculosis (TB) is caused by a bacterium cal...,1.696,3.969,**A:** Tuberculosis (TB) is caused by a bacter...,NOT_TOXIC,Tuberculosis (TB) is caused by a bacterium cal...,NOT_TOXIC,"{""query"": ""What is tuberculosis?"", ""total_matc...","{""query"": ""What is tuberculosis?"", ""answer"": ""...",# Frequently Asked Questions (FAQ)\n\n*Sources...,# Frequently Asked Questions (FAQ)\n\n*Sources...
1,How is TB spread?,FAQ.md,TB is spread through the air from one person t...,0.360,4.524,**A:** TB is spread through the air from one p...,NOT_TOXIC,TB is spread through the air from one person t...,NOT_TOXIC,"{""query"": ""How is TB spread?"", ""total_matches""...","{""query"": ""How is TB spread?"", ""answer"": ""TB i...",# Frequently Asked Questions (FAQ)\n\n*Sources...,# Frequently Asked Questions (FAQ)\n\n*Sources...

In [14]:
dd.columns.to_list()

['query',
 'expected_file',
 'expected_answer',
 'search_time',
 'chat_time',
 'search_answer',
 'search_toxicity',
 'chat_answer',
 'chat_toxicity',
 'search_response',
 'chat_response',
 'ground_truth',
 'ground_truth_sentence']